### ISSUE TITLE
Support for Draco compression

### ISSUE THREAD

**Issue by Zach-Doster** [warrenm/GLTFKit2#20]
Would it be possible to support glb/gltf files that are compressed using Draco?

**Comment by warrenm** [comment]
Draco is an awfully big dependency, and I'm not interested in having it in the source tree of this repository or taking it on as a hard external dependency. We could talk about the best way to introduce a Draco decompression plugin of sorts for people who want it, assuming that change isn't too invasive.

**Comment by warrenm** [comment]
Okay, I've taken a swing at defining a Draco plugin scheme for mesh decompression. Check out 3afcfd3.

To use it, link against Draco in your target, write a class that conforms to the `GLTFDracoMeshDecompressor` protocol, and set the `dracoDecompressorClassName` class property on `GLTFAsset` before loading. 

I've included a sample decompressor implementation in Objective-C++ (see SampleDracoPlugin.h), but it's not enabled because I don't want to include Draco source or binaries in this repository. To test it out, compile Draco for your target of choice, link against it, point Xcode at the appropriate header and library paths, and add the following line before loading Draco-compressed assets:

```swift
GLTFAsset.dracoDecompressorClassName = "DracoDecompressor"
```

Let me know what you think. If this serves your needs we can merge it soon.

**Comment by warrenm** [comment]
This change will be merged and this issue closed in two days if no further response is received.

**Comment by Zach-Doster** [comment]
Okay thanks I'll take a look!

**Comment by warrenm** [comment]
This change will be merged and this issue closed in four days if no further response is received.

**Comment by warrenm** [comment]
Addressed in #21. Please file a new issue if you find this solution not to meet your needs.
