### ISSUE TITLE
Implement support for KHR_mesh_quantization

### ISSUE THREAD

**Issue by lokiiarora** [warrenm/GLTFKit2#32]
Would love to understand what I would need to understand to probably contribute to addition of `KHR_mesh_quantization` support.
I'm new to Obj-c and swift and iOS ecosystem in itself.

**Comment by warrenm** [comment]
We've historically been very ad-hoc when it comes to transforming attributes from one numerical representation to another. I think this extension is an opportunity to take a sounder, more uniform approach.

The essential idea with this extension is that attributes stored in accessors often use unnecessarily large types (such as single-precision float) to store quantities that can represented with little error by smaller types.

I see the implementation of this extension in GLTFKit2 dividing naturally into two separate tasks. First, we need to expand the recognized set of component types for the relevant entity types (e.g., position and texcoords for primitives and morph targets). Second, we need to apply conversions to these types when converting them for use with the supported runtimes (SceneKit, RealityKit, Model I/O), since the component types supported by these runtimes is a subset of the types supported by core glTF 2.0 and this extension.

Since dequantization is applied implicitly through the action of transforms on the data, I think it's reasonable to load the data from the asset as-is, noting its type in metadata (i.e., the accessors' component type), and only converting when absolutely required by the runtime. It has never been in-scope for the framework to aggressively transform asset contents in anticipation of a runtime's needs, so we don't need to do that to handle this extension either.

So that's the broad outline. I don't know when I'll get around to implementing this, but thanks for starting the conversation. We'll use this issue to track progress.

**Comment by lokiiarora** [comment]
Hey @warrenm , thanks for replying to this, if you had to point me to the file where these data-types are dispatched to the underlying rendering framework I'd be able to try my luck at trying to wrap my head around the implementation of this extension.

**Comment by warrenm** [comment]
The biggest offenders are the `GLTFSCNVectorNArrayForAccessor` methods. They handle a very narrow range of source accessor component types and they would need to be completely overhauled to handle mesh quantization, since the set of component types is larger than that required by the core spec (and larger than what SceneKit supports, though I've never sat down and done the testing necessary to discover those exact limits).

**Comment by lokiiarora** [comment]
Acknowledged, thanks for the reply @warrenm .
I'll look into implementing these on my own and contributing back, will use this issue to track progress on the same.
Would request your support for the same.

**Comment by kalyanpusuluri** [comment]
Hey @warrenm when I try to render the compressed glb file it throws an error
The message indicates that the asset you're trying to load or use requires certain extensions that are not supported or available in the context where you're trying to use it.
Asset contains unsupported required extensions: ("KHR_mesh_quantization",     "EXT_meshopt_compression")

Why my file not rendering? Is any thing additionally need to add in our code.

**Comment by warrenm** [comment]
KHR_mesh_quantization and EXT_meshopt_compression both have preliminary support as of 22da88c. I've tested them with all of the sample models I have on-hand, but any feedback is more than welcome.

**Comment by warrenm** [comment]
This issue will be closed as completed in seven days if no further feedback is received. cc @lokiiarora

**Comment by warrenm** [comment]
Closing as complete.
