### ISSUE TITLE
Support for SPM

### ISSUE THREAD

**Issue by JohanAlbrectsen** [warrenm/GLTFKit2#42]
I'm currently lost on how to embed this framework in my project. It's a project, not a .framework or xcframework, so I'm a little lost. Would be such a great help to have support for Swift Package Manager.
Kind regards

**Comment by warrenm** [comment]
A couple of times a year, I waste of a day of my life trying to get SPM to work, and every single time, it's a miserable experience. I have made the offer before (#23) that if someone wants to contribute a working Project.swift file, I'll do my best not to break it. I haven't had any takers so far.

The problem is that many aspects of this project (use of multiple languages, idiosyncratic directory structure, using a framework target rather than a static library) go against the grain of SPM's assumptions, and coaxing it into building a usable library while maintaining compatibility across Obj-C and Swift seems nearly impossible.

In the meantime, if you want to incorporate GLTFKit2 into your project as a framework, you can add the self-contained GLTFKit2 project as a subproject of your Xcode workspace. This will make the GLTFKit2.framework target available in the scope of the workspace, and you can link to it in your own app target(s).

**Comment by warrenm** [comment]
It is now possible to consume GLTFKit2 as an xcframework in Swift projects without the need to compile it yourself or add the project to a workspace. Future tagged releases (starting with 0.5.1) will include updated binaries that incorporate support for KTX2 textures. Draco support remains optionally available via the existing plug-in architecture.

If you have questions or difficulty incorporating the framework in this way, this issue will remain open for the next seven days. Beyond that time, please file new issues detailing your problem or feature request.

**Comment by JohanAlbrectsen** [comment]
Thank you, will try :)

**Comment by JohanAlbrectsen** [comment]
It works now with SPM now, you're a hero! You've saved our team, thank you very much!

**Comment by warrenm** [comment]
Delighted to hear it :)

**Comment by myselfuser1** [comment]
Any support for Cocoapods?

**Comment by warrenm** [comment]
Please don't make new requests on closed issues.

But no, we don't expect to ever support Cocoapods.
