### ISSUE TITLE
Inquiry Regarding Privacy Compliance

### ISSUE THREAD

**Issue by raheel-sadiq-zalando** [warrenm/GLTFKit2#56]
I hope this message finds you well. I'm currently using your library GLTFKit2 in my iOS application, and I'm seeking clarification regarding its privacy implications.

As part of Apple's requirement for iOS applications, it's essential to ensure compliance with privacy guidelines and to be transparent with users about any data collection or usage. Thus, I'd like to inquire about whether GLTFKit2 collects any user data or accesses sensitive user information.
More info: [Privacy Manifest](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files)

**Request for Clarification:**
Could you please provide clarification on the any privacy implications of using GLTFKit2. Any insights or guidance you can offer would be greatly appreciated.

Thank you for your attention to this matter. I look forward to your response.

**Comment by warrenm** [comment]
Thanks for the question. GLTFKit2 does not collect any user data, nor does it access any sensitive user information. 

The binary distributions of GLTFKit2 are provided for the convenience of Swift Package Manager users and do not differ substantively from what would be produced by compiling the framework on your own machine—with the singular exception that the framework links against libktx by default so that the framework consumer doesn't have to compile it themselves.

I'm happy to address any further concerns you might have in this issue. I take user privacy extremely seriously and want to be completely transparent about what goes into the source and binaries I distribute.
