### ISSUE TITLE
Broken surfaces in RealityKit

### ISSUE THREAD

**Issue by agg23** [warrenm/GLTFKit2#59]
This may be an issue with my models, but these are correctly rendered in Blender.

On several different models I have observed various surfaces being transparent in RealityKit on visionOS. Due to difficulty manipulating a 3D object on Vision, I have not been able to confirm if the surface normals are simply reversed. Blender doesn't show this issue.

### Blender

<img width="615" alt="image" src="https://github.com/warrenm/GLTFKit2/assets/238679/3edf4321-08d3-49b7-aba1-6934878cda09">

### visionOS (RealityKit)

<img width="476" alt="image" src="https://github.com/warrenm/GLTFKit2/assets/238679/e0b44654-c648-4cab-9897-9d803d213f2a">

Attached are two different forms of the same simple model that exhibit this issue:
[Brick Repro.zip](https://github.com/warrenm/GLTFKit2/files/15229020/Brick.Repro.zip)

**Comment by warrenm** [comment]
This is a winding order issue. Your model appears correct in Blender because it's doing double-sided rendering, such that winding order doesn't matter. But upon export, I suspect it's writing out primitives that are wound clockwise, which differs from the convention specified by glTF. You should be able to get correct results in RealityKit by reversing the primitive winding order and re-exporting.

For comparison, this is what your model looks like when rendered by Gestaltor, a popular glTF editing tool:
<img width="1113" alt="winding" src="https://github.com/warrenm/GLTFKit2/assets/39937547/5796a61b-ca94-42bc-bd3f-64d97e1d860f">

**Comment by agg23** [comment]
Thank you for your help. I'll look into getting the models fixed. I apologize for my inexperience.

**Comment by warrenm** [comment]
No need to apologize, and don't hesitate to file issues in the future should you encounter any further difficulty. That's how we collectively improve.
