### ISSUE TITLE
GLTFAsset extensions support

### ISSUE THREAD

**Issue by lenkawell** [warrenm/GLTFKit2#63]
I'd like to include some support for the [VRM extensions](https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0/README.md#vrmc_vrmmeta-model-information-required) in our app. However, although .extensionsUsed is set by GLTFAsset.load, .extensions is always null even for GLTF files that I verify have the extension data. I've tried tracing through the code, but so far have not figured out how this could be added.

**Comment by warrenm** [comment]
This occurs because although we parse extensions and extras on everything that derives from `GLTFObject` (including `GLTFAsset`), we don't currently parse extensions contained by the document root object. cgltf parses these as the `data_extensions` property on the `cgltf_gltf` object, but we don't have a natural spot to map that to, since we consider the asset to be the root object, and it can obviously contain extensions and extras of its own.

I think the best way forward would be to add a new dictionary property to `GLTFAsset` to hold document root extensions. Perhaps `rootExtensions` would be a reasonable name?

**Comment by warrenm** [comment]
As of 8f2e65d, new `rootExtensions` and `rootExtras` properties are now implemented on `GLTFAsset`. Obviously to make use of the data they contain you'll need to convert them to objects according to the VRM (or other) extension specifications, but at least they're available now.

If these additions prove satisfactory they can be rolled into a release soon.

**Comment by lenkawell** [comment]
The addition of rootExtensions and rootExtras solves my need for VRM support. Thanks VERY much and especially for the quick response!

**Comment by warrenm** [comment]
Excellent, thanks for confirming. This change has now been incorporated into release [0.5.12](https://github.com/warrenm/GLTFKit2/releases/tag/0.5.12).
